### ISSUE TITLE
Compability probem with Neo4j 4.0

### ISSUE THREAD

**Issue by jg2dev** [LucianoPAlmeida/OGMNeo#35]
Hi!

I'm using this great library to manage a neo4j database in version 4.0.

When I make a create (node) and pass a javascript object, it always gives a syntax error. I understand that it is not adapted to this version, because I am using the latest version (1.0.6). Is it like that or is it a bug in the library?

`
      ogmneo.Node.create(entityToDB, 'Entity')
      .then((node) => 
        node
      ).catch((error) => {
           //Handle error
           console.error(error)
      });
`

`Neo4jError: The old parameter syntax `{param}` is no longer supported. Please use `$param` instead (line 1, column 28 (offset: 27))
"CREATE (n:Entity {  name : {name}, description : {description}, type : {type }) RETURN n"`

Thank you so much!!

**Comment by LucianoPAlmeida** [comment]
Hi @jg2dev 

This is not a bug, is more like an lack of support from my part :(( 
The thing is that the last real feature upadate on this library was more than year ago and because of that the lastest supported version I've tested was 3.5.1 as far as I remember, not really sure and feature wise I think the lastest one dates back to 2018.

As I've moved on to other things the only work done here from that point was security updates(most of them by the bots) so the problem is really that this is unmantained, sorry for that. 
If I find sometime, I can try update and support Neo4j 4.0, but cannot promise anything :) 
And even if I do that I don't recommend to use this library because it is probably going into a path of not maintainance.

But what I do recommend to you is to use [Neode](https://github.com/adam-cowley/neode) library, as it seems properly updated and will probably support version 4.0 and new future versions too. cc @adam-cowley 

Sorry for the inconvenience, I wish I had continued maintaining this library but since middle 2018 I couldn't really do any major work here.

Thank you for reporting this, anyway :)
